name: Auto-Assign PR for reviews
on:
  pull_request:
    types: [opened, reopened]

jobs:
  add-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Reviewer
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Assign PR to awtgerry
        run: gh pr edit ${{ github.event.pull_request.number }} --add-reviewer "awtGerry"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

